### ISSUE TITLE
RuntimeError: web.Application instance initialized with different loop

### ISSUE THREAD

**Issue by Jonathan-Eid** [jersobh/zfs-resty#48]
```
root@hgxcn06:~/zfs-resty# pip install -r requirements.txt
Collecting aiohttp_jinja2==1.6
  Downloading aiohttp_jinja2-1.6-py3-none-any.whl (11 kB)
Collecting aiohttp_cors==0.7.0
  Downloading aiohttp_cors-0.7.0-py3-none-any.whl (27 kB)
Collecting aiohttp==3.9.5
  Downloading aiohttp-3.9.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 1.9 MB/s eta 0:00:00
Collecting python_pam==2.0.2
  Downloading python_pam-2.0.2-py3-none-any.whl (10 kB)
Collecting PyJWT==2.8.0
  Downloading PyJWT-2.8.0-py3-none-any.whl (22 kB)
Collecting pam==0.2.0
  Downloading pam-0.2.0-py3-none-any.whl (976 bytes)
Requirement already satisfied: jinja2>=3.0.0 in /usr/lib/python3/dist-packages (from aiohttp_jinja2==1.6->-r requirements.txt (line 1)) (3.0.3)
Collecting multidict<7.0,>=4.5
  Downloading multidict-6.0.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (124 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.3/124.3 KB 1.5 MB/s eta 0:00:00
Collecting yarl<2.0,>=1.0
  Downloading yarl-1.9.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (301 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 301.6/301.6 KB 1.5 MB/s eta 0:00:00
Requirement already satisfied: attrs>=17.3.0 in /usr/lib/python3/dist-packages (from aiohttp==3.9.5->-r requirements.txt (line 3)) (21.2.0)
Collecting async-timeout<5.0,>=4.0
  Downloading async_timeout-4.0.3-py3-none-any.whl (5.7 kB)
Collecting aiosignal>=1.1.2
  Downloading aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting frozenlist>=1.1.1
  Downloading frozenlist-1.4.1-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (239 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 239.5/239.5 KB 1.4 MB/s eta 0:00:00
Requirement already satisfied: idna>=2.0 in /usr/lib/python3/dist-packages (from yarl<2.0,>=1.0->aiohttp==3.9.5->-r requirements.txt (line 3)) (3.3)
Installing collected packages: python_pam, PyJWT, pam, multidict, frozenlist, async-timeout, yarl, aiosignal, aiohttp, aiohttp_jinja2, aiohttp_cors
  Attempting uninstall: PyJWT
    Found existing installation: PyJWT 2.3.0
    Not uninstalling pyjwt at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'PyJWT'. No files were found to uninstall.
Successfully installed PyJWT-2.8.0 aiohttp-3.9.5 aiohttp_cors-0.7.0 aiohttp_jinja2-1.6 aiosignal-1.3.1 async-timeout-4.0.3 frozenlist-1.4.1 multidict-6.0.5 pam-0.2.0 python_pam-2.0.2 yarl-1.9.4
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

root@hgxcn06:~/zfs-resty# python zfs-resty.py -p 30123
Command 'python' not found, did you mean:
  command 'python3' from deb python3
  command 'python' from deb python-is-python3
root@hgxcn06:~/zfs-resty# python3 zfs-resty.py -p 30123
/root/zfs-resty/zfs-resty.py:83: DeprecationWarning: loop argument is deprecated
  app = aiohttp.web.Application(loop=loop,  middlewares=[auth_middleware])
unhandled exception during asyncio.run() shutdown
task: <Task finished name='Task-1' coro=<_run_app() done, defined at /usr/local/lib/python3.10/dist-packages/aiohttp/web.py:303> exception=RuntimeError('web.Application instance initialized with different loop')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/web.py", line 544, in run_app
    loop.run_until_complete(main_task)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/web.py", line 357, in _run_app
    await runner.setup()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/web_runner.py", line 295, in setup
    self._server = await self._make_server()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/web_runner.py", line 401, in _make_server
    self._app._set_loop(loop)
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/web_app.py", line 262, in _set_loop
    raise RuntimeError(
RuntimeError: web.Application instance initialized with different loop
Traceback (most recent call last):
  File "/root/zfs-resty/zfs-resty.py", line 86, in <module>
    aiohttp.web.run_app(app, host='0.0.0.0', port=args.port)
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/web.py", line 544, in run_app
    loop.run_until_complete(main_task)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/web.py", line 357, in _run_app
    await runner.setup()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/web_runner.py", line 295, in setup
    self._server = await self._make_server()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/web_runner.py", line 401, in _make_server
    self._app._set_loop(loop)
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/web_app.py", line 262, in _set_loop
    raise RuntimeError(
RuntimeError: web.Application instance initialized with different loop

```

**Comment by colin354** [comment]
I meet the same problem, did you solve it?

**Comment by jersobh** [comment]
This repo is a bit outdated. I'll provide a fix tomorrow.

**Comment by jersobh** [comment]
I think it should be fixed. I've also added a install script to make the process smoother. Please, let me know if there's any issue.
